image: python:3.7-stretch
variables:
    AWS_DEFAULT_REGION: us-east-1 
    AWS_ACCESS_KEY_ID: fake_key 
    AWS_SECRET_ACCESS_KEY: fake_secret

before_script:
  - pip install -e .

lint:
  script:
    - pip install -r requirements_lint.txt
    - black --check --diff .
    - flake8

test:2.7:
  image: python:2.7-stretch
  script:
    - pip install -r requirements_test.txt
    - pytest -vv tests --cov kale

test:3.6:
  image: python:3.6-stretch
  script:
    - pip install -r requirements_test.txt
    - pytest -vv tests --cov kale

test:3.7:
  image: python:3.7-stretch
  script:
    - pip install -r requirements_test.txt
    - pytest -vv tests --cov kale
