image: python:3.7-stretch

test:2.7:
  image: python:2.7-stretch
  script:
    - pip install -r requirements.txt
    - pytest tests
test:3.6:
  image: python:3.6-stretch
  script:
    - pip install -r requirements.txt    
    - pytest tests

test:3.7:
  image: python:3.7-stretch
  script:
    - pip install -r requirements.txt
    - pytest tests

