image: python:3.7-stretch

before_script:
  - pip install -r requirements.txt
  - pip install -e .

lint:
  script:
    - yapf --diff --recursive --parallel .
    - flake8

test:2.7:
  image: python:2.7-stretch
  script:
    - pytest tests

test:3.6:
  image: python:3.6-stretch
  script:
    - pytest tests

test:3.7:
  image: python:3.7-stretch
  script:
    - pytest tests
