image: python:3.7-stretch

services:
  - docker:dind


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: fake_key
  AWS_SECRET_ACCESS_KEY: fake_secret

before_script:
  - curl -fsSL https://get.docker.com | bash
  - pip install -e .

lint:
  image: python:3.7-stretch
  services: []
  before_script: []
  script:
    - pip install -r requirements_lint.txt
    - black --check --diff .
    - flake8

test:2.7:
  script:
    - pip install -r requirements_test.txt
    - pytest -vv tests --cov chili-pepper

test:3.6:
  script:
    - pip install -r requirements_test.txt
    - pytest -vv tests --cov chili-pepper

test:3.7:
  script:
    - pip install -r requirements_test.txt
    - pytest -vv tests --cov chili-pepper
